markdown: kramdown

title: Open Legal Data
author: Open Legal Data
email: hello@openlegaldata.io
icon: fa-balance-scale
description: > # this means to ignore newlines until "baseurl:"
  Free Access to Legal Information.

twitter_username: openlegaldata
github_username:  openlegaldata
google_analytics: UA-1090820-32
plugins:
    # - jekyll-paginate-v2
    # - jekyll-paginate
    - jekyll-feed

sass:
  style: compressed    # or :expanded, :nested, etc.
  sass_dir: _sass      # default; change only if you move your partials

exclude:
    - Gemfile
    - Gemfile.lock

# Pagination Settings
# paginate: 3
# paginate_path: "/blog/page:num/"

#pagination:  # for v2
#    enabled: true
#    per_page: 3
#    permalink: '/page/:num/'
#    title: ':title - page :num of :max'
#    limit: 0
#    sort_field: 'date'
#    sort_reverse: true
